server:
  persistentVolume:
    enabled: true
    storageClass: "ceph-rbd"
    size: 40Gi
  
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi

  securityContext:
    seccompProfile:
      type: RuntimeDefault
  
  retention: "365d"
  retentionSize: "35GB"

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
      
configmapReload:
  prometheus:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

prometheus-node-exporter:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
      add: ["SYS_TIME"]

extraScrapeConfigs: |
  - job_name: caddy
    scheme: http
    static_configs:
      - targets: ['192.168.1.253:2019']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'caddy'

  - job_name: caddy_public
    scheme: http
    static_configs:
      - targets: ['192.168.1.20:2019']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'caddy_public'

  - job_name: cloudflared_public
    scheme: http
    static_configs:
      - targets: ['192.168.1.20:2000']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'cloudflared_public'

  - job_name: 'crowdsec'
    scheme: http
    static_configs:
      - targets: ['192.168.1.20:6060']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'crowdsec'

  - job_name: 'cloudflared'
    scheme: http
    static_configs:
      - targets: ['192.168.1.19:2000']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'cloudflared'

  - job_name: minio-cluster
    scheme: http
    static_configs:
      - targets: ['192.168.1.252:9000']
    metrics_path: /minio/v2/metrics/cluster
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'minio'
  
  - job_name: minio-node
    scheme: http
    static_configs:
      - targets: ['192.168.1.252:9000']
    metrics_path: /minio/v2/metrics/node
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'minio'
  
  - job_name: minio-bucket
    scheme: http
    static_configs:
      - targets: ['192.168.1.252:9000']
    metrics_path: /minio/v2/metrics/bucket
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'minio'
  
  - job_name: minio-resource
    scheme: http
    static_configs:
      - targets: ['192.168.1.252:9000']
    metrics_path: /minio/v2/metrics/resource
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'minio'

  - job_name: ceph-cluster
    honor_labels: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - '192.168.1.244:9283'
        - '192.168.1.245:9283'
        - '192.168.1.246:9283'
        - '192.168.1.247:9283'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: ceph_cluster
        replacement: ceph

  - job_name: kube-manager
    scheme: https
    static_configs:
      - targets: ['kube-manager.home.jasongodson.com']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'kube-manager'

  - job_name: issue-to-pr
    scheme: https
    static_configs:
      - targets: ['issue-to-pr.home.jasongodson.com']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'issue-to-pr'

  - job_name: treasure-takedown-matchmaker
    scheme: https
    static_configs:
      - targets: ['matchmaker.home.jasongodson.com']
    metrics_path: /treasure-takedown/admin/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'matchmaker-treasure'

  - job_name: botb-matchmaker
    scheme: https
    static_configs:
      - targets: ['matchmaker.home.jasongodson.com']
    metrics_path: /battle-of-the-brains/admin/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'matchmaker-botb'

  - job_name: budget-app
    scheme: https
    static_configs:
      - targets: ['budget.home.jasongodson.com']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'budget-app'

prometheus-pushgateway:
  enabled: false

alertmanager:
  enabled: false
