version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: REDACTED_TOKEN
    ca:
        crt: REDACTED_BASE64
        key: REDACTED_BASE64
    certSANs:
        - 192.168.1.30
        - 192.168.1.31
        - 192.168.1.32
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        interfaces:
            - interface: ens18
              dhcp: true
              vip:
                ip: 192.168.1.250
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.9.5
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: REDACTED_ID
    secret: REDACTED_SECRET
    controlPlane:
        endpoint: https://192.168.1.250:6443
    clusterName: cluster-private
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: REDACTED_TOKEN
    secretboxEncryptionSecret: REDACTED_SECRET
    ca:
        crt: REDACTED_BASE64
        key: REDACTED_BASE64
    aggregatorCA:
        crt: REDACTED_BASE64
        key: REDACTED_BASE64
    serviceAccount:
        key: REDACTED_BASE64
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.32.2
        certSANs:
            - 192.168.1.30
            - 192.168.1.31
            - 192.168.1.32
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.32.2
    proxy:
        image: registry.k8s.io/kube-proxy:v1.32.2
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.32.2
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: REDACTED_BASE64
            key: REDACTED_BASE64
    allowSchedulingOnControlPlanes: true
